# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 666)
        MainWindow.setStyleSheet('background-image: url("home_background.png")')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet('background-image: url("home_background.png")')

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 120, 771, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutWidget.setStyleSheet("background:transparent;")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.chekbox_res = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chekbox_res.setObjectName("chekbox_res")

        self.gridLayout_2.addWidget(self.chekbox_res, 2, 0, 1, 2)

        self.line_dump = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_dump.setObjectName("line_dump")
        self.line_dump.setStyleSheet("background:transparent;")

        self.gridLayout_2.addWidget(self.line_dump, 1, 1, 1, 1)

        self.btn_dump = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_dump.setObjectName("btn_dump")
        self.btn_dump.setStyleSheet("background: #415374;")

        self.gridLayout_2.addWidget(self.btn_dump, 1, 0, 1, 1)

       # self.checkbox_need_mean = QtWidgets.QCheckBox(self.gridLayoutWidget)
       # self.checkbox_need_mean.setObjectName("checkbox_need_mean")

       # self.gridLayout_2.addWidget(self.checkbox_need_mean, 3, 0, 1, 2)

        self.btn_res = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_res.setObjectName("btn_res")
        self.btn_res.setStyleSheet("background: #415374;")

        self.gridLayout_2.addWidget(self.btn_res, 5, 0, 1, 1)

        self.label_res_info = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_res_info.setObjectName("label_res_info")

        self.gridLayout_2.addWidget(self.label_res_info, 4, 0, 1, 2)

        self.line_res = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_res.setObjectName("line_res")

        self.gridLayout_2.addWidget(self.line_res, 5, 1, 1, 1)

        self.label_dump = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_dump.setObjectName("label_dump")

        self.gridLayout_2.addWidget(self.label_dump, 0, 0, 1, 2)

        self.btn_start_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_stop.setGeometry(QtCore.QRect(490, 600, 111, 28))
        self.btn_start_stop.setObjectName("btn_start_stop")
        self.btn_start_stop.setStyleSheet("background: #415374;")

        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_settings.setGeometry(QtCore.QRect(300, 600, 93, 28))
        self.btn_settings.setObjectName("btn_settings")
        self.btn_settings.setStyleSheet("background: #415374;")

        self.label_rts_status = QtWidgets.QLabel(self.centralwidget)
        self.label_rts_status.setGeometry(QtCore.QRect(10, 10, 820, 16))
        self.label_rts_status.setObjectName("label_rts_status")
        self.label_rts_status.setStyleSheet("background:transparent;")

        self.table_real_res = QtWidgets.QTableWidget(self.centralwidget)
        self.table_real_res.setGeometry(QtCore.QRect(40, 440, 771, 141))
        self.table_real_res.setObjectName("table_real_res")
        self.table_real_res.setColumnCount(0)
        self.table_real_res.setRowCount(0)

        self.rbt_mode_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbt_mode_2.setGeometry(QtCore.QRect(280, 380, 361, 31))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.rbt_mode_2.setFont(font)
        self.rbt_mode_2.setObjectName("rbt_mode_2")
        self.rbt_mode_2.setStyleSheet("background:transparent;")

        self.rbt_mode_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbt_mode_1.setGeometry(QtCore.QRect(310, 60, 301, 20))
        self.rbt_mode_1.setStyleSheet("background:transparent;")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbt_mode_1.sizePolicy().hasHeightForWidth())
        self.rbt_mode_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbt_mode_1.setFont(font)
        self.rbt_mode_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rbt_mode_1.setObjectName("rbt_mode_1")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 320, 300, 16))
        self.label.setObjectName("label")
        self.label.setStyleSheet("background:transparent;")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chekbox_res.setText(_translate("MainWindow", "Подробная сводка"))
        self.btn_dump.setText(_translate("MainWindow", "Выбрать"))
      #  self.checkbox_need_mean.setText(_translate("MainWindow", "Нужно ли вывести график?"))
        self.btn_res.setText(_translate("MainWindow", "Выбрать"))
        self.label_res_info.setText(_translate("MainWindow", "Выберите место сохранения сводки анализа"))
        self.label_dump.setText(_translate("MainWindow", "Выберите дамп для анализа"))
        self.btn_start_stop.setText(_translate("MainWindow", "Запуск"))
        self.btn_settings.setText(_translate("MainWindow", "Настройки"))
        self.label_rts_status.setText(_translate("MainWindow", "test"))
        self.rbt_mode_2.setText(_translate("MainWindow", "Анализ в реальном времени"))
        self.rbt_mode_1.setText(_translate("MainWindow", "Статический анализ"))
        self.label.setText(_translate("MainWindow", "Результат анализа: "))
