# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from old_ui import *
from variable import variable
from pathlib import Path




from dataset_prepare import dataset_prepare
import time
from dump_parser import parser
import threading

from learn_and_calc import calc, learn, rt_calc
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 620)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 620))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 620))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet('background-image: url("home_background.png")')
        self.centralwidget.setObjectName("centralwidget")
        self.rb1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb1.setGeometry(QtCore.QRect(95, 150, 70, 20))
        self.rb1.setObjectName("rb1")
        self.rb1.setStyleSheet("background:transparent;")
        self.rb2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb2.setGeometry(QtCore.QRect(300, 150, 151, 20))
        self.rb2.setObjectName("rb2")
        self.rb2.setStyleSheet("background:transparent;")
        self.rb3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb3.setGeometry(QtCore.QRect(570, 150, 95, 20))
        self.rb3.setObjectName("rb3")
        self.rb3.setStyleSheet("background:transparent;")
        self.rb4 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb4.setGeometry(QtCore.QRect(880, 150, 201, 20))
        self.rb4.setObjectName("rb4")
        self.rb4.setStyleSheet("background:transparent;")

        self.button_group = QtWidgets.QButtonGroup()
        self.button_group.addButton(self.rb1, 1)
        self.button_group.addButton(self.rb2, 2)
        self.button_group.addButton(self.rb3, 3)
        self.button_group.addButton(self.rb4, 4)
        self.button_group.idClicked.connect(self.pr_mode)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 80, 301, 20))
        self.label.setObjectName("label")
        self.label.setStyleSheet("background:transparent;")
        self.separator_1 = QtWidgets.QFrame(self.centralwidget)
        self.separator_1.setGeometry(QtCore.QRect(240, 130, 20, 411))
        self.separator_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.separator_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_1.setObjectName("separator_1")
        #self.separator_1.setStyleSheet("background:transparent;")
        self.separator_2 = QtWidgets.QFrame(self.centralwidget)
        self.separator_2.setGeometry(QtCore.QRect(480, 130, 20, 411))
        self.separator_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.separator_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_2.setObjectName("separator_2")
        #self.separator_2.setStyleSheet("background:transparent;")
        self.separator_3 = QtWidgets.QFrame(self.centralwidget)
        self.separator_3.setGeometry(QtCore.QRect(730, 130, 20, 411))
        self.separator_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.separator_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator_3.setObjectName("separator_3")
        #self.separator_3.setStyleSheet("background:transparent;")
        self.dump_choice_button = QtWidgets.QPushButton(self.centralwidget)
        self.dump_choice_button.setStyleSheet('background-color: #415374')
        self.dump_choice_button.setGeometry(QtCore.QRect(80, 250, 93, 28))
        self.dump_choice_button.setObjectName("dump_choice_button")
        self.dump_choice_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dump_choice_line.setGeometry(QtCore.QRect(33, 200, 190, 22))
        self.dump_choice_line.setObjectName("dump_choice_line")
        self.need_mean = QtWidgets.QCheckBox(self.centralwidget)
        self.need_mean.setGeometry(QtCore.QRect(20, 310, 211, 20))
        self.need_mean.setObjectName("need_mean")
        self.need_mean.setStyleSheet("background:transparent;")
        self.need_saved = QtWidgets.QCheckBox(self.centralwidget)
        self.need_saved.setGeometry(QtCore.QRect(20, 350, 201, 20))
        self.need_saved.setObjectName("need_saved")
        self.need_saved.setStyleSheet("background:transparent;")
        self.dir_choice_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dir_choice_line.setGeometry(QtCore.QRect(33, 420, 190, 22))
        self.dir_choice_line.setObjectName("dir_choice_line")
        self.dir_choice_button = QtWidgets.QPushButton(self.centralwidget)
        self.dir_choice_button.setGeometry(QtCore.QRect(60, 480, 121, 28))
        self.dir_choice_button.setObjectName("dir_choice_button")
        self.dataset_dump_choice_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dataset_dump_choice_line.setGeometry(QtCore.QRect(275, 200, 190, 22))
        self.dataset_dump_choice_line.setObjectName("dataset_dump_choice_line")
        self.dataset_dump_choice_button = QtWidgets.QPushButton(self.centralwidget)
        self.dataset_dump_choice_button.setGeometry(QtCore.QRect(325, 250, 93, 28))
        self.dataset_dump_choice_button.setObjectName("dataset_dump_choice_button")
        self.dataset_dir_choice_button = QtWidgets.QPushButton(self.centralwidget)
        self.dataset_dir_choice_button.setGeometry(QtCore.QRect(300, 480, 131, 28))
        self.dataset_dir_choice_button.setObjectName("dataset_dir_choice_button")
        self.dataset_dir_choice_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dataset_dir_choice_line.setGeometry(QtCore.QRect(275, 420, 190, 22))
        self.dataset_dir_choice_line.setObjectName("dataset_dir_choice_line")
        self.dataset_choice_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dataset_choice_line.setGeometry(QtCore.QRect(518, 200, 190, 22))
        self.dataset_choice_line.setObjectName("dataset_choice_line")
        self.dataset_choice_button = QtWidgets.QPushButton(self.centralwidget)
        self.dataset_choice_button.setGeometry(QtCore.QRect(555, 250, 121, 28))
        self.dataset_choice_button.setObjectName("dataset_choice_button")
        self.svm_variable = QtWidgets.QLineEdit(self.centralwidget)
        self.svm_variable.setGeometry(QtCore.QRect(518, 360, 190, 22))
        self.svm_variable.setObjectName("svm_variable")
        self.knn_variable = QtWidgets.QLineEdit(self.centralwidget)
        self.knn_variable.setGeometry(QtCore.QRect(518, 410, 190, 22))
        self.knn_variable.setObjectName("knn_variable")
        self.boost_variable = QtWidgets.QLineEdit(self.centralwidget)
        self.boost_variable.setGeometry(QtCore.QRect(518, 460, 190, 22))
        self.boost_variable.setObjectName("boost_variable")
        self.default_learn = QtWidgets.QCheckBox(self.centralwidget)
        self.default_learn.setGeometry(QtCore.QRect(500, 290, 231, 41))
        self.default_learn.setObjectName("default_learn")
        self.default_learn.setStyleSheet("background:transparent;")
        self.rts_results = QtWidgets.QTableView(self.centralwidget)
        self.rts_results.setGeometry(QtCore.QRect(750, 200, 441, 311))
        self.rts_results.setObjectName("rts_results")
        self.rts_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.rts_analyze.setGeometry(QtCore.QRect(770, 530, 131, 28))
        self.rts_analyze.setObjectName("rts_analyze")
        self.rts_stop = QtWidgets.QPushButton(self.centralwidget)
        self.rts_stop.setGeometry(QtCore.QRect(1030, 530, 131, 28))
        self.rts_stop.setObjectName("rts_stop")
        self.spravka = QtWidgets.QPushButton(self.centralwidget)
        self.spravka.setGeometry(QtCore.QRect(555, 500, 121, 28))
        self.spravka.setObjectName("spravka")
        self.pusk = QtWidgets.QPushButton(self.centralwidget)
        self.pusk.setGeometry(QtCore.QRect(300, 550, 131, 35))
        self.pusk.setObjectName("pusk")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.working()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rb1.setText(_translate("MainWindow", "Анализ"))
        self.rb2.setText(_translate("MainWindow", "Подготовка датасета"))
        self.rb3.setText(_translate("MainWindow", "Обучение"))
        self.rb4.setText(_translate("MainWindow", "Анализ в реальном времени"))
        self.label.setText(_translate("MainWindow", "Пожалуйста, выберите режим работы программы"))
        self.dump_choice_button.setText(_translate("MainWindow", "Выбор дампа"))
        self.need_mean.setText(_translate("MainWindow", "Нужно ли вывести график?"))
        self.need_saved.setText(_translate("MainWindow", "Нужно ли сохранить график?"))
        self.dir_choice_button.setText(_translate("MainWindow", "Выбор директории"))
        self.dataset_dump_choice_button.setText(_translate("MainWindow", "Выбор дампа"))
        self.dataset_dir_choice_button.setText(_translate("MainWindow", "Выбор директории"))
        self.dataset_choice_button.setText(_translate("MainWindow", "Выбор датасета"))
        self.default_learn.setText(_translate("MainWindow", "Настройки обучения по умолчанию"))
        self.rts_analyze.setText(_translate("MainWindow", "Запустить анализ"))
        self.rts_stop.setText(_translate("MainWindow", "Остановить анализ"))
        self.spravka.setText(_translate("MainWindow", "Справка"))
        self.pusk.setText(_translate("MainWindow", "ПУСК"))

    def working(self):
        self.pusk.clicked.connect(analyze)
        self.dump_choice_button.clicked.connect(self.dumped)
        self.dir_choice_button.clicked.connect(self.saved)
        self.dataset_dump_choice_button.clicked.connect(self.dataset_dumped)
        self.dataset_dir_choice_button.clicked.connect(self.dataset_saved)
        self.dataset_choice_button.clicked.connect(self.dataset)
        self.rts_analyze.clicked.connect(start_rts_in_bg)
        self.rts_stop.clicked.connect(variable.rts_analyze_stop)


    def block_ui(self):
        self.pusk.setEnabled(False)
        self.dump_choice_button.setEnabled(False)
        self.dir_choice_button.setEnabled(False)
        self.dump_choice_line.setEnabled(False)
        self.dir_choice_line.setEnabled(False)
        self.need_mean.setEnabled(False)
        self.need_saved.setEnabled(False)

        self.dataset_dump_choice_button.setEnabled(False)
        self.dataset_dir_choice_button.setEnabled(False)
        self.dataset_dump_choice_line.setEnabled(False)
        self.dataset_dir_choice_line.setEnabled(False)

        self.dataset_choice_button.setEnabled(False)
        self.dataset_choice_line.setEnabled(False)
        self.default_learn.setEnabled(False)
        self.spravka.setEnabled(False)
        self.svm_variable.setEnabled(False)
        self.knn_variable.setEnabled(False)
        self.boost_variable.setEnabled(False)

        self.rts_analyze.setEnabled(False)
        self.rts_stop.setEnabled(False)

    def block_rb(self):
        self.rb1.setEnabled(False)
        self.rb2.setEnabled(False)
        self.rb3.setEnabled(False)
        self.rb4.setEnabled(False)

    def pr_mode(self, mode):
        variable.change_program_mode(mode)
        if mode == 1:
            self.pusk.setEnabled(True)
            self.dump_choice_button.setEnabled(True)
            self.dir_choice_button.setEnabled(True)
            self.dump_choice_line.setEnabled(True)
            self.dir_choice_line.setEnabled(True)
            self.need_mean.setEnabled(True)
            self.need_saved.setEnabled(True)

            self.dataset_dump_choice_button.setEnabled(False)
            self.dataset_dir_choice_button.setEnabled(False)
            self.dataset_dump_choice_line.setEnabled(False)
            self.dataset_dir_choice_line.setEnabled(False)

            self.dataset_choice_button.setEnabled(False)
            self.dataset_choice_line.setEnabled(False)
            self.default_learn.setEnabled(False)
            self.spravka.setEnabled(False)
            self.svm_variable.setEnabled(False)
            self.knn_variable.setEnabled(False)
            self.boost_variable.setEnabled(False)
            self.rts_analyze.setEnabled(False)
            self.rts_stop.setEnabled(False)
        elif mode == 2:
            self.pusk.setEnabled(True)
            self.dump_choice_button.setEnabled(False)
            self.dir_choice_button.setEnabled(False)
            self.dump_choice_line.setEnabled(False)
            self.dir_choice_line.setEnabled(False)
            self.need_mean.setEnabled(False)
            self.need_saved.setEnabled(False)

            self.dataset_dump_choice_button.setEnabled(True)
            self.dataset_dir_choice_button.setEnabled(True)
            self.dataset_dump_choice_line.setEnabled(True)
            self.dataset_dir_choice_line.setEnabled(True)

            self.dataset_choice_button.setEnabled(False)
            self.dataset_choice_line.setEnabled(False)
            self.default_learn.setEnabled(False)
            self.spravka.setEnabled(False)
            self.svm_variable.setEnabled(False)
            self.knn_variable.setEnabled(False)
            self.boost_variable.setEnabled(False)

            self.rts_analyze.setEnabled(False)
            self.rts_stop.setEnabled(False)
        elif mode == 3:
            self.pusk.setEnabled(True)
            self.dump_choice_button.setEnabled(False)
            self.dir_choice_button.setEnabled(False)
            self.dump_choice_line.setEnabled(False)
            self.dir_choice_line.setEnabled(False)
            self.need_mean.setEnabled(False)
            self.need_saved.setEnabled(False)

            self.dataset_dump_choice_button.setEnabled(False)
            self.dataset_dir_choice_button.setEnabled(False)
            self.dataset_dump_choice_line.setEnabled(False)
            self.dataset_dir_choice_line.setEnabled(False)

            self.dataset_choice_button.setEnabled(True)
            self.dataset_choice_line.setEnabled(True)
            self.default_learn.setEnabled(True)
            self.spravka.setEnabled(True)
            self.svm_variable.setEnabled(True)
            self.knn_variable.setEnabled(True)
            self.boost_variable.setEnabled(True)

            self.rts_analyze.setEnabled(False)
            self.rts_stop.setEnabled(False)
        elif mode == 4:
            self.pusk.setEnabled(False)
            self.dump_choice_button.setEnabled(False)
            self.dir_choice_button.setEnabled(False)
            self.dump_choice_line.setEnabled(False)
            self.dir_choice_line.setEnabled(False)
            self.need_mean.setEnabled(False)
            self.need_saved.setEnabled(False)

            self.dataset_dump_choice_button.setEnabled(False)
            self.dataset_dir_choice_button.setEnabled(False)
            self.dataset_dump_choice_line.setEnabled(False)
            self.dataset_dir_choice_line.setEnabled(False)

            self.dataset_choice_button.setEnabled(False)
            self.dataset_choice_line.setEnabled(False)
            self.default_learn.setEnabled(False)
            self.spravka.setEnabled(False)
            self.svm_variable.setEnabled(False)
            self.knn_variable.setEnabled(False)
            self.boost_variable.setEnabled(False)

            self.rts_analyze.setEnabled(True)
            self.rts_stop.setEnabled(True)

    def return_mode_state(self):
        self.rb1.setEnabled(True)
        self.rb2.setEnabled(True)
        self.rb3.setEnabled(True)
        self.rb4.setEnabled(True)

    def saved(self):
        filename = QtWidgets.QFileDialog.getExistingDirectory(self, "Select a Directory")
        if filename:
            path = Path(filename)
            print(path)
        # save_dir_path = str(QFileDialog.getExistingDirectory(self, "Select Directory"))
        # variable.change_save_path(filename)
        # res_save_path = variable.path_of_save
        # c.create_text(115, 325, text=res_save_path, font=('arial', 10, 'normal'))


    def dumped(self):
        filename = QtWidgets.QFileDialog.getOpenFileNames(
            self,
            "Select Files",
            r"C:\\images\\",
            "Images (*.png *.jpg)"
        )
        variable.change_path(filename)
        file_name = os.path.basename("r'" + variable.path)

    def dataset(self):
        filename = fd.askopenfilename(filetypes=(("xlsx", "*.xlsx"), ("all files", "*.*")))
        variable.change_dataset_path(filename)
        file_name = os.path.basename("r'" + variable.dataset_path)

    def dataset_dumped(self):
        filename = fd.askopenfilename(filetypes=(("pcapng", "*.pcapng"), ("all files", "*.*")))
        variable.change_prepare_set_path(filename)
        file_name = os.path.basename("r'" + variable.prepare_set_path)

    def dataset_saved(self):
        save = fd.askdirectory()
        variable.change_save_prepare_path(save)
        res_save_path = variable.prepare_set_save_path

    def msg_error(self,title,mes):
            msg = QMessageBox()
            msg.setWindowTitle(title)
            msg.setText(mes)
            msg.setIcon(QMessageBox.Icon.Critical)
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
    def msg_res(self,title,mes):
            msg = QMessageBox()
            msg.setWindowTitle(title)
            msg.setText(mes)
            msg.setIcon(QMessageBox.Icon.Information)
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()


dump_file = os.getcwd() + '\\dump.csv'
stop_rts = False



# Функция завершения работы программы
def quit_program():
    variable.quit = 1
    dump_file = os.getcwd() + '\\dump.csv'
    prepareset_path = os.getcwd() + '\\prepareset.csv'
    if os.path.exists(dump_file):
        os.remove(dump_file)
    if os.path.exists(prepareset_path):
        os.remove(prepareset_path)


# Получение пути дампа

# Кнопка ПУСК

def analyze():
    title = "Ошибка"
    ui.block_ui()
    ui.block_rb()

    if variable.mode == 1:
        #variable.change_save_diag(Check_savediag.get())
        #variable.change_mean_diag(Check_diag.get())

        if variable.path is None:
            ui.return_mode_state()
            ui.msg_error(title, "Не выбран дамп для анализа")
            return None
        elif variable.path_of_save is None:
            ui.msg_error(title, "Не выбрана директория для сохранения результатов")
            ui.return_mode_state()
            return None
        elif not (os.path.isfile('svm_model.joblib' or 'knn_model.joblib' or 'boost_model.joblib')):
            ui.msg_error(title, "Одна из моделей не обучена")
            ui.return_mode_state()
            return None
        else:
            mode = 1
            time_start = time.perf_counter()
            parser(variable.path, dump_file, mode)
            calc(dump_file, mode)
            time_elapsed = "{:2.2f}".format(time.perf_counter() - time_start)
            msg = "Анализ завершён.\n\nЗатраченное время: " + str(time_elapsed) + ' секунд(ы)' + '\n'
            ui.msg_res("Результаты анализа",msg)
            ui.return_mode_state()
    elif variable.mode == 2:
        if variable.dataset_path is None:
            ui.msg_error(title, "Не выбран датасет для обучения")
            ui.return_mode_state()
            return None
        else:
            time_start = time.perf_counter()
            variable.change_svm_count(spin_svm.get())
            variable.change_knn_count(spin_knn.get())
            variable.change_boost_count(spin_boost.get())
            learn(variable.dataset_path)
            if not variable.check_learn:
                ui.return_mode_state()
                ui.msg_error(title, "Датасет неправильно размечен")
                return None

            time_elapsed = "{:2.2f}".format(time.perf_counter() - time_start)
            msg1 = 'SVC Score: ' + '\n' + str(variable.report1) + '\n' + '\n'
            msg2 = 'k-NN Score: ' + '\n' + str(variable.report2) + '\n' + '\n'
            msg3 = 'Boost Score: ' + '\n' + str(variable.report3) + '\n' + '\n'
            msg4 = 'Затраченное время: ' + str(time_elapsed) + ' секунд(ы)' + '\n' + '\n'
            msg = msg1 + msg2 + msg3 + msg4
            ui.msg_res("Результаты обучения", msg)
            ui.return_mode_state()
    elif variable.mode == 3:
        if variable.prepare_set_path is None or variable.prepare_set_save_path is None:
            ui.msg_error(title, "Не выбран дамп для подготовки датасета или директория для сохранения")
            ui.return_mode_state()
            return None
        else:
            time_start = time.perf_counter()
            dataset_prepare()
            ui.return_mode_state()
            time_elapsed = "{:2.2f}".format(time.perf_counter() - time_start)
            msg = "Формирование датасета завершено.\n\nЗатраченное время: " + str(time_elapsed) + ' секунд(ы)' + '\n'
            ui.msg_res("Формирование датасета", msg)
            return None

def start_analyze_in_bg():
    threading.Thread(target=analyze).start()
def start_rts_in_bg():
    threading.Thread(target=rts_analyze_func).start()

def rts_analyze_func():
    mode = 2
    path = ''
    while not variable.stop_rts:
        parser(mode, dump_file, path)
        calc(dump_file,mode)
        time.sleep(0.1)
    return None


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.block_ui()
    MainWindow.show()
    sys.exit(app.exec_())